//
//  Data.swift
//  CloneSettings
//
//  Created by a.kravcov on 29.07.2021.
//

import Foundation
import UIKit

class Data {
    
    let data = [
            "Section0": [Model(type: .switch,
                               title: "Авиарежим",
                               isOn: false,
                               image: UIImage(systemName: "airplane"),
                               color: UIColor.systemOrange),
                         Model(type: .descr,
                               title: "Wi-Fi",
                               descr: "test wi-fi",
                               image: UIImage(systemName: "wifi"),
                               color: UIColor.systemBlue),
                         Model(type: .descr,
                               title: "Bluetooth",
                               descr: "Вкл.",
                               image: UIImage(named: "bluetooth"),
                               color: UIColor.systemBlue),
                         Model(type: .plain,
                               title: "Сотовая связь",
                               image: UIImage(systemName: "antenna.radiowaves.left.and.right"),
                               color: UIColor.systemGreen),
                         Model(type: .descr,
                               title: "Режим модема",
                               descr: "Выкл.",
                               image: UIImage(systemName: "personalhotspot"),
                               color: UIColor.systemGreen),
                         Model(type: .switch,
                               title: "VPN",
                               isOn: true,
                               image: UIImage(systemName: "globe"),
                               color: UIColor.systemBlue)],
            "Section1": [Model(type: .plain,
                               title: "Уведомления",
                               image: UIImage(systemName: "note"),
                               color: UIColor.systemRed),
                         Model(type: .plain,
                               title: "Звук, тактильные сигналы",
                               image: UIImage(systemName: "speaker.wave.3.fill"),
                               color: UIColor.systemPink),
                         Model(type: .plain,
                               title: "Не беспокоить",
                               image: UIImage(systemName: "moon.fill"),
                               color: UIColor.systemIndigo),
                         Model(type: .plain,
                               title: "Экранное время",
                               image: UIImage(systemName: "hourglass"),
                               color: UIColor.systemIndigo)],
            "Section2": [Model(type: .plain,
                               title: "Основные",
                               image: UIImage(systemName: "gear"),
                               color: UIColor.systemGray),
                         Model(type: .plain,
                               title: "Пункт управления",
                               image: UIImage(systemName: "slider.horizontal.3"),
                               color: UIColor.systemBlue),
                         Model(type: .plain,
                               title: "Экран и яркость",
                               image: UIImage(systemName: "textformat.size"),
                               color: UIColor.systemBlue),
                         Model(type: .plain,
                               title: "Экран \"Домой\"",
                               image: UIImage(systemName: "apps.iphone"),
                               color: UIColor.systemIndigo),
                         Model(type: .plain,
                               title: "Универсальный доступ",
                               image: UIImage(systemName: "figure.stand"),
                               color: UIColor.systemBlue),
                         Model(type: .plain,
                               title: "Обои",
                               image: UIImage(systemName: "seal"),
                               color: UIColor.systemTeal),
                         Model(type: .plain,
                               title: "Siri и Поиск",
                               image: UIImage(named: "siri"),
                               color: UIColor.systemIndigo),
                         Model(type: .plain,
                               title: "Face ID и код-пароль",
                               image: UIImage(systemName: "person.fill.viewfinder"),
                               color: UIColor.systemGreen),
                         Model(type: .plain,
                               title: "Аккумулятор",
                               image: UIImage(systemName: "battery.100"),
                               color: UIColor.systemGreen),
                         Model(type: .plain,
                               title: "Конфиденциальность",
                               image: UIImage(systemName: "hand.raised.fill"),
                               color: UIColor.systemBlue)]]
}
